### ISSUE TITLE
FIXMES markdown and commands

### ISSUE THREAD

**Issue by Thanatermesis** [FOSSClass/AbantOS-Elive#27]
From "creating a repository" to "Linux distributions" there's some Markdown code which is worng, also the commands/code should be reviewed so they don't looks totally correct

**Comment by Hephzibah21** [comment]
Honestly all **_emojis_** are boring they are too little and boring as in I want **Elive/Nature** such as; 
wild-animals forests/tree,the sound of wind blowing on the trees, the sound of leaves and birds, water falls, rain, lightening and thunderstorms, flying clouds and snowfall, sun-rise and sun-set with brilliant horizon!  just ELive. These emojis are not natural they make me sick, so many and fake. Check out all the emoji faces and fake fruits yikes! I'm thinking how I can come up with life/natural emojis for Elive anyone interested? lol just exploring how to use styling and markdown.

**Comment by Hephzibah21** [comment]
I saw these commands when I was exploring GitHub and I thought i could share with the FossClass.

**- GitHub for windows**     []( http://windows.github.com)

**GitHub for Mac**                 [](http://mac.github.com   )

Git distributions for Linux and Posix Systems are available on the official Git SCM website

**Git for all platforms**           []( http://git.scm.com)

## to configure User information for all local repositories;

`$ git config --global user.name   "[name]" (sets the name you want attached to your commit transactions)

$ git config --global user-email "[email address]" (sets the email you attached to your commit transactions

**create repositories**

Start a new repository or obtain one from an existing URL
$ git init [project-name]  (creates a new local repository with the special name.

$ git clone [url]  (downloads a project and it's entire Version history).

**Make changes**
$ git status  (lists all new or modified files to be ommited).

**Group changes**
$ git branch  (lists all local branches in the current repo)

$git branch  [branch-name]  (creates a new branch)

$ git checkout [branch-name]  (switches to the specified branch and updates working directory)

$ git merge [branch-name]  (combines the specified branch's history into the current branch).

$git branch -d[branch-name]  (deletes the specified branch).

**Comment by Hephzibah21** [comment]
I just wanted to share those commands to FossClass. and experience styling with markdown. I think the commands are useful and quick cheat chat.

**Comment by Hephzibah21** [comment]
I hope the TM who  were doing commands will be able to edit the commands.
Thanks.
