### ISSUE TITLE
Gif wallpaper problems

### ISSUE THREAD

**Issue by Thanatermesis** [FOSSClass/AbantOS-Elive#28]
In the line 493 explains how to use a gif as wallpaper, this is not suggested since will constanty consumes cpu but also there's some bugs with the GIF library which may look distorted (wrong diagonal aspect), also, the suggested dir to use is $HOME/.e/e17/backgrounds instead of the one in /usr

**Comment by Thanatermesis** [comment]
The correct way to make animated wallpapers is to create it in edje (edc) and program how it should act, but this will require programming knowledges

**Comment by Hephzibah21** [comment]
Sure we really don’t need it. We have time to short out every thing this weekend. I will have a look at the collections and editing tomorrow too. 🙏🏿
